[tasks.update]
description = "Update packages"
run = "pnpm up"

[tasks.install]
description = "Install packages"
run = "pnpm install"

[tasks.dev]
description = "Run development server"
run = "pnpm dev"

[tasks.prepare]
description = "Prepare local environment"
run = ["brew install vercel-cli", "vercel"]

[tasks.lint]
description = "Run linter"
run = ["pnpm lint --fix", "pnpm format --fix"]
